# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

env:
  - PKG_TARBALL=sqpr.tar.gz

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  - tlmgr install index


after_success:
    - tar -C .. -xf $PKG_TARBALL
    - xvfb-run Rscript -e 'covr::codecov()'
    - xvfb-run Rscript -e 'pkgdown::build_site(); pkgdown::deploy_site_github()'
