# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown


warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site(); pkgdown::deploy_site_github()'
